// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL0bSQ4n56519yCq_Pa-R_TAiYqSLtpOA',
    appId: '1:950042372653:web:2f0581d2430fef242726a4',
    messagingSenderId: '950042372653',
    projectId: 'capstonejbnuteam8',
    authDomain: 'capstonejbnuteam8.firebaseapp.com',
    databaseURL: 'https://capstonejbnuteam8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstonejbnuteam8.appspot.com',
    measurementId: 'G-K9P0FN61K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUXC8xbVRdAgtbxhce2lK8whCIZmsETGQ',
    appId: '1:950042372653:android:6bb3190d35bc10dc2726a4',
    messagingSenderId: '950042372653',
    projectId: 'capstonejbnuteam8',
    databaseURL: 'https://capstonejbnuteam8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstonejbnuteam8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKcaSeMZnWboqPUjrsqMyFaBWfCpWv9mc',
    appId: '1:950042372653:ios:d683f504bc040c742726a4',
    messagingSenderId: '950042372653',
    projectId: 'capstonejbnuteam8',
    databaseURL: 'https://capstonejbnuteam8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstonejbnuteam8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
