mock_courses = {
    'course_id_1': {'course_name': '데이터베이스', 'time': ['월1', '월2'], 'type': '전공선택', 'department': '소프트웨어공', 'building': '공과대학 3호관', 'grade': 3},
    'course_id_2': {'course_name': '운영체제', 'time': ['화3', '목1'], 'type': '전공필수', 'department': '소프트웨어공', 'building': '공과대학 2호관', 'grade': 3},
    'course_id_3': {'course_name': '소프트웨어공학', 'time': ['수2', '금1'], 'type': '전공선택', 'department': '컴퓨터공학과', 'building': '공과대학 1호관', 'grade': 4},
    'course_id_4': {'course_name': '알고리즘', 'time': ['월3', '수3'], 'type': '전공선택', 'department': '소프트웨어공', 'building': '공과대학 3호관', 'grade': 3},
    'course_id_5': {'course_name': '네트워크', 'time': ['화2', '목2'], 'type': '전공필수', 'department': '컴퓨터공학과', 'building': '공과대학 1호관', 'grade': 3},
    'course_id_6': {'course_name': '웹프로그래밍', 'time': ['월4', '수4'], 'type': '전공선택', 'department': '컴퓨터공학과', 'building': '공과대학 2호관', 'grade': 3},
    'course_id_7': {'course_name': '인공지능', 'time': ['화5', '목5'], 'type': '전공선택', 'department': '소프트웨어공', 'building': '공과대학 1호관', 'grade': 4},
    'course_id_8': {'course_name': '컴퓨터구조', 'time': ['월5', '수5'], 'type': '전공필수', 'department': '컴퓨터공학과', 'building': '공과대학 3호관', 'grade': 3},
    'course_id_9': {'course_name': '데이터마이닝', 'time': ['화4', '목4'], 'type': '전공선택', 'department': '컴퓨터공학과', 'building': '공과대학 2호관', 'grade': 4},
    'course_id_10': {'course_name': '영어회화', 'time': ['월2'], 'type': '교양', 'building': '인문대학 1호관'},
    'course_id_11': {'course_name': '철학의 이해', 'time': ['화4'], 'type': '교양', 'building': '인문대학 2호관'},
    'course_id_12': {'course_name': '현대사회와 윤리', 'time': ['수3'], 'type': '교양', 'building': '사회과학대학 1호관'},
    'course_id_13': {'course_name': '경제학개론', 'time': ['월1', '월2'], 'type': '교양', 'building': '공과대학 3호관'},
    'course_id_14': {'course_name': '미술의 이해', 'time': ['금1'], 'type': '교양', 'building': '예술대학 1호관'},
    'course_id_15': {'course_name': '음악의 이해', 'time': ['금2'], 'type': '교양', 'building': '예술대학 2호관'},
    'course_id_16': {'course_name': '체육', 'time': ['월5'], 'type': '교양', 'building': '체육관'},
    'course_id_17': {'course_name': '수영', 'time': ['화5'], 'type': '교양', 'building': '수영장'},
    'course_id_18': {'course_name': '스포츠댄스', 'time': ['수5'], 'type': '교양', 'building': '체육관'},
    'course_id_19': {'course_name': '요가', 'time': ['목5'], 'type': '교양', 'building': '체육관'},
    'course_id_20': {'course_name': '필라테스', 'time': ['금5'], 'type': '교양', 'building': '체육관'},
}
